// components/pilot/data.ts

import type {Encounter, Practitioner, Kpi} from '@/types/pilot';

export const practitioners: Practitioner[] = [
  {name: 'dr Ferdi Iskandar', degree: '', role: 'Dokter / Auditor', strNumber: 'STR-2024-0847', strExpiry: '2027-03-15', totalEncounters: 142},
  {name: 'Josep Arianto', degree: '', role: 'Triage Officer', strNumber: 'STR-2024-1203', strExpiry: '2026-11-20', totalEncounters: 89},
  {name: 'Novia Angraini', degree: '', role: 'Dokter', strNumber: 'STR-2024-0912', strExpiry: '2027-06-01', totalEncounters: 56},
  {name: 'dr Lusiana Dewi', degree: '', role: 'Dokter', strNumber: 'STR-2024-1055', strExpiry: '2027-01-10', totalEncounters: 72},
  {name: 'dr Boyong Baskoro', degree: 'SPOG', role: 'Spesialis / Auditor', strNumber: 'STR-2024-0634', strExpiry: '2028-08-22', totalEncounters: 115},
  {name: 'Oriza Rahmawati', degree: 'Amd.Keb', role: 'Bidan / Auditor', strNumber: 'STR-2024-1478', strExpiry: '2026-09-10', totalEncounters: 68},
  {name: 'dr Dibya Arfianda', degree: 'SPOG', role: 'Spesialis / Auditor', strNumber: 'STR-2024-0721', strExpiry: '2028-04-18', totalEncounters: 104},
];

export const encounters: Encounter[] = [
  {
    id: 'REQ-99283-X',
    date: '2026-06-18',
    time: '18:12:45',
    practitioner: 'dr Ferdi Iskandar',
    role: 'Dokter / Auditor',
    encounterType: 'Imaging',
    location: 'Puskesmas Balowerti',
    agent: 'Imaging-V3',
    confidence: 0.994,
    icd10: 'A15.0',
    description: 'Interpretasi CXR untuk Batuk Kronis. Agent mendeteksi opasitas di lobus kanan atas.',
    verified: true,
    verifiedBy: 'dr Ferdi Iskandar',
    source: 'Assist',
  },
  {
    id: 'REQ-99282-A',
    date: '2026-06-18',
    time: '18:09:12',
    practitioner: 'Josep Arianto',
    role: 'Triage Officer',
    encounterType: 'Triage',
    location: 'RSUD Dr. Soedono',
    agent: 'Cardio-Core',
    confidence: 0.978,
    icd10: 'R00.1',
    description: 'Analisis Irama EKG. Terdeteksi Sinus Bradycardia dengan Normal Axis.',
    verified: false,
    source: 'Assist',
  },
  {
    id: 'REQ-99281-B',
    date: '2026-06-18',
    time: '17:55:30',
    practitioner: 'Novia Angraini',
    role: 'Dokter',
    encounterType: 'Lab Interpretasi',
    location: 'Lab Sentral',
    agent: 'Endo-Agent',
    confidence: 0.991,
    icd10: 'E11.9',
    description: 'Orkestrasi Hasil Lab: HbA1c 7,2%. Penilaian risiko diabetes melitus tipe 2 selesai.',
    verified: true,
    verifiedBy: 'dr Lusiana Dewi',
    source: 'Assist',
  },
  {
    id: 'REQ-99280-M',
    date: '2026-06-18',
    time: '17:42:01',
    practitioner: 'dr Lusiana Dewi',
    role: 'Dokter',
    encounterType: 'Pertumbuhan Anak',
    location: 'Klinik Satria',
    agent: 'Peds-Oracle',
    confidence: 0.955,
    icd10: 'Z00.1',
    description: 'Analisis Grafik Pertumbuhan Anak. Pasien berada di persentil ke-85 untuk berat badan.',
    verified: true,
    verifiedBy: 'dr Ferdi Iskandar',
    source: 'Sidelab',
  },
  {
    id: 'REQ-99279-K',
    date: '2026-06-17',
    time: '16:33:18',
    practitioner: 'dr Boyong Baskoro',
    role: 'Spesialis / Auditor',
    encounterType: 'ANC',
    location: 'Puskesmas Balowerti',
    agent: 'OBGYN-Agent',
    confidence: 0.987,
    icd10: 'Z34.0',
    description: 'Pemeriksaan ANC trimester kedua. USG menunjukkan pertumbuhan janin sesuai usia gestasi 22 minggu.',
    verified: true,
    verifiedBy: 'dr Boyong Baskoro',
    source: 'Assist',
  },
  {
    id: 'REQ-99278-F',
    date: '2026-06-17',
    time: '15:21:44',
    practitioner: 'Oriza Rahmawati',
    role: 'Bidan / Auditor',
    encounterType: 'ANC',
    location: 'Klinik Satria',
    agent: 'OBGYN-Agent',
    confidence: 0.962,
    icd10: 'Z34.9',
    description: 'Kunjungan ANC rutin. Tekanan darah 120/80, TFU sesuai usia kehamilan, DJJ normal 142 bpm.',
    verified: true,
    verifiedBy: 'dr Boyong Baskoro',
    source: 'Sidelab',
  },
  {
    id: 'REQ-99277-P',
    date: '2026-06-17',
    time: '14:08:56',
    practitioner: 'dr Dibya Arfianda',
    role: 'Spesialis / Auditor',
    encounterType: 'Diagnostik',
    location: 'RSUD Dr. Soedono',
    agent: 'Neuro-Core',
    confidence: 0.943,
    icd10: 'G43.9',
    description: 'Konsultasi neurologi: migrain tanpa aura. Riwayat serangan berulang, CT scan normal.',
    verified: true,
    verifiedBy: 'dr Dibya Arfianda',
    source: 'Assist',
  },
  {
    id: 'REQ-99276-D',
    date: '2026-06-16',
    time: '11:45:22',
    practitioner: 'dr Ferdi Iskandar',
    role: 'Dokter / Auditor',
    encounterType: 'Resep Review',
    location: 'Puskesmas Balowerti',
    agent: 'Pharma-Check',
    confidence: 0.996,
    icd10: 'I10',
    description: 'Review resep hipertensi. DDI check: Amlodipine 5mg + Metformin 500mg — tidak ada interaksi signifikan.',
    verified: true,
    verifiedBy: 'dr Ferdi Iskandar',
    source: 'Assist',
  },
  {
    id: 'REQ-99275-H',
    date: '2026-06-16',
    time: '10:30:11',
    practitioner: 'Josep Arianto',
    role: 'Triage Officer',
    encounterType: 'Emergency',
    location: 'RSUD Dr. Soedono',
    agent: 'Triage-V2',
    confidence: 0.981,
    icd10: 'R55',
    description: 'Triage pasien sinkop. GCS 14, TD 90/60, nadi 110. Prioritas merah — rujukan segera ke IGD.',
    verified: true,
    verifiedBy: 'dr Lusiana Dewi',
    source: 'Assist',
  },
  {
    id: 'REQ-99274-W',
    date: '2026-06-16',
    time: '09:15:33',
    practitioner: 'Novia Angraini',
    role: 'Dokter',
    encounterType: 'Diagnostik',
    location: 'Puskesmas Balowerti',
    agent: 'Diag-General',
    confidence: 0.934,
    icd10: 'J18.9',
    description: 'Demam 5 hari, nyeri perut, mual. Widal 1/320. Diagnosis: Demam Tifoid.',
    verified: true,
    verifiedBy: 'dr Ferdi Iskandar',
    source: 'Sidelab',
  },
  {
    id: 'REQ-99273-E',
    date: '2026-06-15',
    time: '16:48:07',
    practitioner: 'dr Lusiana Dewi',
    role: 'Dokter',
    encounterType: 'Lab Interpretasi',
    location: 'Lab Sentral',
    agent: 'Endo-Agent',
    confidence: 0.988,
    icd10: 'E03.9',
    description: 'Interpretasi panel tiroid: TSH 8,2 mIU/L (tinggi), FT4 normal. Hipotiroidisme subklinis.',
    verified: true,
    verifiedBy: 'dr Lusiana Dewi',
    source: 'Assist',
  },
  {
    id: 'REQ-99272-N',
    date: '2026-06-15',
    time: '14:22:51',
    practitioner: 'Oriza Rahmawati',
    role: 'Bidan / Auditor',
    encounterType: 'Pertumbuhan Anak',
    location: 'Klinik Satria',
    agent: 'Peds-Oracle',
    confidence: 0.971,
    icd10: 'Z00.1',
    description: 'Imunisasi DPT-HB-Hib dosis 3. Berat badan 8,2 kg (persentil 50), panjang badan 72 cm.',
    verified: true,
    verifiedBy: 'dr Boyong Baskoro',
    source: 'Sidelab',
  },
  {
    id: 'REQ-99271-R',
    date: '2026-06-15',
    time: '11:05:38',
    practitioner: 'dr Boyong Baskoro',
    role: 'Spesialis / Auditor',
    encounterType: 'Imaging',
    location: 'RSUD Dr. Soedono',
    agent: 'Imaging-V3',
    confidence: 0.992,
    icd10: 'O14.0',
    description: 'USG obstetri: preeklampsia ringan. Tekanan darah 145/92, proteinuria +1. Monitoring ketat.',
    verified: true,
    verifiedBy: 'dr Boyong Baskoro',
    source: 'Assist',
  },
  {
    id: 'REQ-99270-C',
    date: '2026-06-14',
    time: '17:33:29',
    practitioner: 'dr Dibya Arfianda',
    role: 'Spesialis / Auditor',
    encounterType: 'Diagnostik',
    location: 'Puskesmas Balowerti',
    agent: 'Neuro-Core',
    confidence: 0.956,
    icd10: 'M54.5',
    description: 'Nyeri punggung bawah kronis. MRI menunjukkan HNP L4-L5 tanpa kompresi saraf signifikan.',
    verified: true,
    verifiedBy: 'dr Dibya Arfianda',
    source: 'Assist',
  },
  {
    id: 'REQ-99269-V',
    date: '2026-06-14',
    time: '13:18:44',
    practitioner: 'dr Ferdi Iskandar',
    role: 'Dokter / Auditor',
    encounterType: 'Triage',
    location: 'Puskesmas Balowerti',
    agent: 'Triage-V2',
    confidence: 0.985,
    icd10: 'R10.9',
    description: 'Triage nyeri perut akut. Nyeri kuadran kanan bawah, McBurney (+). Rujuk appendisitis.',
    verified: true,
    verifiedBy: 'dr Ferdi Iskandar',
    source: 'Assist',
  },
  {
    id: 'REQ-99268-J',
    date: '2026-06-14',
    time: '10:42:16',
    practitioner: 'Josep Arianto',
    role: 'Triage Officer',
    encounterType: 'Emergency',
    location: 'RSUD Dr. Soedono',
    agent: 'Triage-V2',
    confidence: 0.989,
    icd10: 'I21.9',
    description: 'Triage nyeri dada. EKG menunjukkan ST elevasi di lead II, III, aVF. STEMI inferior — cath lab.',
    verified: true,
    verifiedBy: 'dr Lusiana Dewi',
    source: 'Assist',
  },
];

export const kpis: Kpi[] = [
  {
    label: 'Total Encounter',
    value: '14.204',
    delta: '+18%',
    positive: true,
    spark: '0,21 9,19 18,17 27,15 36,14 45,12 55,10 64,8 73,6 82,4 91,3 100,1',
  },
  {
    label: 'Keyakinan Klinis',
    value: '98,2%',
    delta: '+0,8pp',
    positive: true,
    spark: '0,18 9,17 18,15 27,13 36,11 45,10 55,8 64,6 73,5 82,3 91,2 100,1',
  },
  {
    label: 'Terverifikasi',
    value: '94,1%',
    delta: '+2,3pp',
    positive: true,
    spark: '0,20 9,18 18,16 27,14 36,12 45,10 55,8 64,6 73,5 82,3 91,2 100,1',
  },
  {
    label: 'Agent Aktif',
    value: '128',
    delta: '+12',
    positive: true,
    spark: '0,16 9,15 18,14 27,13 36,12 45,11 55,9 64,7 73,6 82,4 91,3 100,2',
  },
];

export const certifications = [
  {label: 'STR dr Ferdi Iskandar', expiry: '2027-03-15', daysRemaining: 268},
  {label: 'SIP Puskesmas Balowerti', expiry: '2026-12-01', daysRemaining: 164},
  {label: 'Sertifikat BLS/ACLS', expiry: '2026-09-10', daysRemaining: 82},
  {label: 'Pelatihan PPE', expiry: '2026-08-01', daysRemaining: 42},
  {label: 'STR Oriza Rahmawati', expiry: '2026-09-10', daysRemaining: 82},
  {label: 'Akreditasi Klinik', expiry: '2027-06-15', daysRemaining: 360},
];
